name: Discord Notifier

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MESSAGE: ${{ github.event.comment.body || github.event.issue.title }}
        run: |
          curl -X POST \
          https://discord.com/api/webhooks/${DISCORD_WEBHOOK_URL} \
          -H 'Content-Type: application/json' \
          -d '{"content": "${MESSAGE}"}'
